development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://drakenfaye.herokuapp.com/faye"
  secret_token: "73f9ded1d77115cde6a1e9c3726628882f5fc8affe35cec2b55a1229892b74d8"
  signature_expiration: 3600 # one hour
