# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b44f235845537ebc7f6943351f8293f68f60306b4f28769e668b2e26667dc00c8197ce099b55bec18c480ccf758e36f7a6170814f058a4302c9da7f6e11752ed

test:
  secret_key_base: 422075751482b14635b312ca1c47b43b64c864680fb5eae288649afbf7a1beff7f9a2ad73407a592a7994fb502809cd3e8e62697d29fe3667560051adfa026f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
